keybinds:
  bindings:
    "0": "debug"
    "Escape": "pauseMenu"
    "A": "walkLeft"
    "S": "walkBackward"
    "D": "walkRight"
    "Tab": "onlinePlayers"
    "W": "walkForward"
    "Enter": "chat"
language: "English"