joey:
  texture: youngster
  pokemon:
    - speciesId: pikachu
      level: 80
      moveIds:
        - quickattack
        - thundershock
    - speciesId: pikachu
      level: 10
      moveIds:
        - quickattack
        - thundershock

timmy:
  texture: youngster
  pokemon: 
    - speciesId: eevee
      level: 15
      moveIds:
        - quickattack
        - tackle

josh:
  texture: youngster
  pokemon: 
    - speciesId: snivy
      level: 12
      moveIds:
        - vinewhip
        - leaftornado
