ident: "house_Rival_1F"
index: 5
triggers:
- type: "Teleport"
  x: 95
  y: 6
  width: 35
  height: 9
  idx: 0
- type: "Collision"
  x: 0
  y: 6
  width: 96
  height: 4
  idx: -1
- type: "Collision"
  x: 127
  y: 7
  width: 33
  height: 4
  idx: -1
- type: "Collision"
  x: 81
  y: 104
  width: 15
  height: 15
  idx: -1
- type: "Collision"
  x: 65
  y: 104
  width: 14
  height: 5
  idx: -1
- type: "Collision"
  x: 79
  y: 55
  width: 33
  height: 33
  idx: -1
- type: "Collision"
  x: 48
  y: 72
  width: 15
  height: 36
  idx: -1
- type: "Collision"
  x: 1
  y: 105
  width: 46
  height: 9
  idx: -1
- type: "Collision"
  x: 0
  y: 9
  width: 5
  height: 105
  idx: -1
- type: "Teleport"
  x: 144
  y: 121
  width: 16
  height: 16
  idx: 1
- type: "Collision"
  x: 158
  y: 10
  width: 2
  height: 100
  idx: -1
- type: "Collision"
  x: 95
  y: 118
  width: 44
  height: 3
  idx: -1
- type: "Collision"
  x: 142
  y: 139
  width: 17
  height: 2
  idx: -1
- type: "Collision"
  x: 138
  y: 123
  width: 2
  height: 17
  idx: -1
teleports:
- map: 0
  target: 3
- map: 6
  target: 0
actors: {}