ident: "house_Protagonist_2F"
index: 8
triggers:
- type: "Collision"
  x: 34
  y: 15
  width: 182
  height: 8
  idx: -1
- type: "Collision"
  x: 194
  y: 19
  width: 29
  height: 152
  idx: -1
- type: "Collision"
  x: 13
  y: 160
  width: 184
  height: 11
  idx: -1
- type: "Collision"
  x: 15
  y: 16
  width: 33
  height: 148
  idx: -1
- type: "Collision"
  x: 49
  y: 120
  width: 9
  height: 2
  idx: -1
- type: "Collision"
  x: 89
  y: 120
  width: 23
  height: 3
  idx: -1
- type: "Collision"
  x: 48
  y: 148
  width: 148
  height: 5
  idx: -1
- type: "Teleport"
  x: 64
  y: 120
  width: 18
  height: 4
  idx: 0
teleports:
- map: 2
  target: 1
actors:
  "tv":
    texture: "actor_size"
    index: 0
    x: 108
    y: 111
    script:
    - "tv"
    - "dialog 1"
  "gc":
    texture: "actor_size"
    index: 1
    x: 130
    y: 114
    script:
    - "gc"
    - "dialog 1"
  "book":
    texture: "actor_size"
    index: 2
    x: 156
    y: 118
    script:
    - "book"
    - "dialog 1"
  "pc":
    texture: "actor_size"
    index: 3
    x: 176
    y: 122
    script:
    - "pcY"
    - "dialog 1"
  "bed":
    texture: "actor_size"
    index: 4
    x: 157
    y: 62
    script:
    - "bedY"
    - "dialog 2"
wildEncounters: []