ident: "house_Rival_1F"
index: 5
triggers:
- type: "Collision"
  x: 182
  y: 143
  width: 2
  height: 0
  idx: -1
- type: "Collision"
  x: 10
  y: 31
  width: 13
  height: 143
  idx: -1
- type: "Collision"
  x: 9
  y: 183
  width: 176
  height: 5
  idx: -1
- type: "Collision"
  x: 23
  y: 31
  width: 95
  height: 8
  idx: -1
- type: "Collision"
  x: 152
  y: 29
  width: 31
  height: 10
  idx: -1
- type: "Collision"
  x: 24
  y: 135
  width: 30
  height: 15
  idx: -1
- type: "Collision"
  x: 104
  y: 137
  width: 14
  height: 12
  idx: -1
- type: "Collision"
  x: 104
  y: 88
  width: 30
  height: 29
  idx: -1
- type: "Teleport"
  x: 120
  y: 49
  width: 30
  height: 5
  idx: 0
- type: "Collision"
  x: 112
  y: 31
  width: 45
  height: 6
  idx: -1
- type: "Collision"
  x: 191
  y: 27
  width: 2
  height: 151
  idx: -1
- type: "Collision"
  x: 104
  y: 151
  width: 42
  height: 14
  idx: -1
- type: "Collision"
  x: 20
  y: 165
  width: 126
  height: 16
  idx: -1
- type: "Teleport"
  x: 160
  y: 150
  width: 23
  height: 25
  idx: 1
teleports:
- map: 0
  target: 3
- map: 6
  target: 0
actors:
  "tv":
    texture: "actor_size"
    index: 0
    x: 86
    y: 143
    script:
    - "tv"
    - "dialog 1"
  "fridge":
    texture: "actor_size"
    index: 1
    x: 55
    y: 136
    script:
    - "fridge"
    - "dialog 1"
wildEncounters: []