ident: "house_Rival_2F"
index: 6
triggers:
- type: "Collision"
  x: 71
  y: 132
  width: 30
  height: 12
  idx: -1
- type: "Collision"
  x: 39
  y: 146
  width: 62
  height: 14
  idx: -1
- type: "Collision"
  x: 170
  y: 29
  width: 12
  height: 140
  idx: -1
- type: "Collision"
  x: 22
  y: 29
  width: 152
  height: 3
  idx: -1
- type: "Collision"
  x: 21
  y: 32
  width: 15
  height: 138
  idx: -1
- type: "Collision"
  x: 33
  y: 171
  width: 150
  height: 6
  idx: -1
teleports:
- map: 5
  target: 1
actors:
  "books_left":
    texture: "actor_size"
    index: 0
    x: 100
    y: 138
    script:
    - "bookL"
    - "dialog 1"
  "books_right":
    texture: "actor_size"
    index: 1
    x: 117
    y: 137
    script:
    - "bookR"
    - "dialog 1"
  "pc":
    texture: "actor_size"
    index: 2
    x: 38
    y: 132
    script:
    - "pc"
    - "dialog 1"
  "tv":
    texture: "actor_size"
    index: 3
    x: 24
    y: 163
    script:
    - "tv"
    - "dialog 1"
  "console":
    texture: "actor_size"
    index: 4
    x: 85
    y: 67
    script:
    - "console"
    - "dialog 1"
  "bed":
    texture: "actor_size"
    index: 5
    x: 36
    y: 37
    script:
    - "bedNY"
    - "dialog 1"
wildEncounters: []