ident: "house_Protagonist_1F"
index: 2
triggers:
- type: "Teleport"
  x: 49
  y: 36
  width: 29
  height: 5
  idx: 0
- type: "Collision"
  x: 15
  y: 23
  width: 15
  height: 139
  idx: -1
- type: "Collision"
  x: 26
  y: 21
  width: 203
  height: 3
  idx: -1
- type: "Collision"
  x: 209
  y: 21
  width: 13
  height: 157
  idx: -1
- type: "Collision"
  x: 89
  y: 175
  width: 124
  height: 3
  idx: -1
- type: "Collision"
  x: 83
  y: 157
  width: 8
  height: 20
  idx: -1
- type: "Collision"
  x: 29
  y: 161
  width: 58
  height: 7
  idx: -1
- type: "Collision"
  x: 95
  y: 142
  width: 41
  height: 27
  idx: -1
- type: "Collision"
  x: 138
  y: 125
  width: 69
  height: 26
  idx: -1
- type: "Teleport"
  x: 59
  y: 124
  width: 26
  height: 21
  idx: 1
teleports:
- map: 0
  target: 1
- map: 8
  target: 0
actors:
  "tv":
    texture: "actor_size"
    index: 0
    x: 127
    y: 87
    script:
    - "tv"
    - "dialog 1"
  "mum":
    texture: "actor_size"
    index: 1
    x: 160
    y: 61
    script:
    - "mum"
    - "dialog 3"
wildEncounters: []