ident: "house_Protagonist_2F"
index: 7
triggers:
- type: "Collision"
  x: 42
  y: 6
  width: 157
  height: 3
  idx: -1
- type: "Collision"
  x: 190
  y: 6
  width: 4
  height: 132
  idx: -1
- type: "Collision"
  x: 46
  y: 7
  width: 5
  height: 131
  idx: -1
- type: "Collision"
  x: 47
  y: 103
  width: 14
  height: 3
  idx: -1
- type: "Collision"
  x: 83
  y: 104
  width: 29
  height: 3
  idx: -1
- type: "Collision"
  x: 82
  y: 107
  width: 5
  height: 18
  idx: -1
- type: "Collision"
  x: 58
  y: 105
  width: 3
  height: 24
  idx: -1
- type: "Collision"
  x: 61
  y: 125
  width: 26
  height: 4
  idx: -1
- type: "Collision"
  x: 127
  y: 104
  width: 34
  height: 3
  idx: -1
- type: "Collision"
  x: 158
  y: 46
  width: 21
  height: 26
  idx: -1
- type: "Collision"
  x: 188
  y: 89
  width: 5
  height: 13
  idx: -1
teleports:
- map: 2
  target: 1
actors:
  "tv":
    texture: "actor_size"
    index: 0
    x: 112
    y: 104
    script:
    - "tv"
    - "dialog 1"
  "gc":
    texture: "actor_size"
    index: 1
    x: 130
    y: 98
    script:
    - "gc"
    - "dialog 1"
  "book":
    texture: "actor_size"
    index: 2
    x: 158
    y: 103
    script:
    - "book"
    - "dialog 1"
  "pc":
    texture: "actor_size"
    index: 3
    x: 175
    y: 107
    script:
    - "pcY"
    - "dialog 1"
  "bed":
    texture: "actor_size"
    index: 4
    x: 160
    y: 61
    script:
    - "bedY"
    - "dialog 2"
wildEncounters: []