ident: "house_Protagonist_2F"
index: 3
triggers:
- type: "Collision"
  x: 42
  y: 6
  width: 157
  height: 3
  idx: -1
- type: "Collision"
  x: 190
  y: 6
  width: 4
  height: 132
  idx: -1
- type: "Collision"
  x: 46
  y: 7
  width: 5
  height: 131
  idx: -1
- type: "Collision"
  x: 47
  y: 103
  width: 14
  height: 3
  idx: -1
- type: "Collision"
  x: 83
  y: 104
  width: 29
  height: 3
  idx: -1
- type: "Collision"
  x: 82
  y: 107
  width: 5
  height: 18
  idx: -1
- type: "Collision"
  x: 58
  y: 105
  width: 3
  height: 24
  idx: -1
- type: "Collision"
  x: 61
  y: 125
  width: 26
  height: 4
  idx: -1
- type: "Collision"
  x: 111
  y: 96
  width: 18
  height: 28
  idx: -1
- type: "Collision"
  x: 127
  y: 104
  width: 34
  height: 3
  idx: -1
- type: "Collision"
  x: 130
  y: 98
  width: 14
  height: 14
  idx: -1
- type: "Collision"
  x: 157
  y: 99
  width: 35
  height: 18
  idx: -1
teleports:
- map: 2
  target: 1
actors: {}