ident: "house_Rival_2F"
index: 6
triggers:
- type: "Teleport"
  x: 129
  y: 120
  width: 14
  height: 12
  idx: 0
- type: "Collision"
  x: 16
  y: 4
  width: 128
  height: 7
  idx: -1
- type: "Collision"
  x: 15
  y: 4
  width: 3
  height: 100
  idx: -1
- type: "Collision"
  x: 16
  y: 104
  width: 16
  height: 21
  idx: -1
- type: "Collision"
  x: 31
  y: 117
  width: 20
  height: 4
  idx: -1
- type: "Collision"
  x: 48
  y: 101
  width: 31
  height: 17
  idx: -1
- type: "Collision"
  x: 80
  y: 104
  width: 32
  height: 31
  idx: -1
- type: "Collision"
  x: 143
  y: 9
  width: 1
  height: 109
  idx: -1
- type: "Collision"
  x: 112
  y: 118
  width: 10
  height: 3
  idx: -1
- type: "Collision"
  x: 127
  y: 136
  width: 19
  height: 3
  idx: -1
- type: "Collision"
  x: 145
  y: 110
  width: 3
  height: 31
  idx: -1
- type: "Collision"
  x: 119
  y: 118
  width: 3
  height: 20
  idx: -1
- type: "Collision"
  x: 122
  y: 135
  width: 5
  height: 5
  idx: -1
teleports:
- map: 5
  target: 1
actors: {}