ident: "house_Protagonist_1F"
index: 2
triggers:
- type: "Teleport"
  x: 49
  y: 5
  width: 30
  height: 9
  idx: 0
- type: "Collision"
  x: 29
  y: 5
  width: 21
  height: 7
  idx: -1
- type: "Collision"
  x: 29
  y: 4
  width: 7
  height: 137
  idx: -1
- type: "Collision"
  x: 30
  y: 138
  width: 6
  height: 1
  idx: -1
- type: "Collision"
  x: 92
  y: 105
  width: 5
  height: 35
  idx: -1
- type: "Collision"
  x: 94
  y: 120
  width: 44
  height: 4
  idx: -1
- type: "Collision"
  x: 138
  y: 105
  width: 2
  height: 27
  idx: -1
- type: "Collision"
  x: 137
  y: 106
  width: 70
  height: 3
  idx: -1
- type: "Collision"
  x: 206
  y: 7
  width: 3
  height: 148
  idx: -1
- type: "Collision"
  x: 79
  y: 7
  width: 130
  height: 4
  idx: -1
- type: "Collision"
  x: 130
  y: 25
  width: 29
  height: 30
  idx: -1
- type: "Collision"
  x: 112
  y: 26
  width: 5
  height: 29
  idx: -1
- type: "Collision"
  x: 171
  y: 24
  width: 5
  height: 32
  idx: -1
- type: "Collision"
  x: 34
  y: 105
  width: 21
  height: 6
  idx: -1
- type: "Collision"
  x: 145
  y: 72
  width: 29
  height: 15
  idx: -1
- type: "Teleport"
  x: 62
  y: 104
  width: 21
  height: 20
  idx: 1
teleports:
- map: 0
  target: 1
- map: 8
  target: 0
actors:
  "tv":
    texture: "actor_size"
    index: 0
    x: 128
    y: 72
    script:
    - "tv"
    - "dialog 1"
  "mum":
    texture: "actor_size"
    index: 1
    x: 158
    y: 42
    script:
    - "mum"
    - "dialog 3"
wildEncounters: []