ident: "lab_oak"
index: 3
triggers:
- type: "Teleport"
  x: 108
  y: 5
  width: 25
  height: 9
  idx: 0
- type: "Collision"
  x: 17
  y: 9
  width: 14
  height: 27
  idx: -1
- type: "Collision"
  x: 14
  y: 8
  width: 4
  height: 210
  idx: -1
- type: "Collision"
  x: 13
  y: 212
  width: 214
  height: 7
  idx: -1
- type: "Collision"
  x: 222
  y: 6
  width: 7
  height: 212
  idx: -1
- type: "Collision"
  x: 209
  y: 8
  width: 14
  height: 29
  idx: -1
- type: "Collision"
  x: 144
  y: 65
  width: 79
  height: 30
  idx: -1
- type: "Collision"
  x: 161
  y: 177
  width: 62
  height: 28
  idx: -1
- type: "Collision"
  x: 112
  y: 185
  width: 48
  height: 10
  idx: -1
- type: "Collision"
  x: 107
  y: 177
  width: 5
  height: 18
  idx: -1
- type: "Collision"
  x: 17
  y: 175
  width: 94
  height: 12
  idx: -1
- type: "Collision"
  x: 18
  y: 137
  width: 13
  height: 31
  idx: -1
- type: "Collision"
  x: 30
  y: 119
  width: 36
  height: 41
  idx: -1
- type: "Collision"
  x: 11
  y: 6
  width: 89
  height: 3
  idx: -1
- type: "Collision"
  x: 138
  y: 7
  width: 86
  height: 2
  idx: -1
- type: "Collision"
  x: 145
  y: 131
  width: 46
  height: 17
  idx: -1
- type: "Collision"
  x: 16
  y: 71
  width: 79
  height: 23
  idx: -1
teleports: []
actors:
  "machine":
    texture: "actor_size"
    index: 0
    x: 40
    y: 119
    script:
    - "machine"
    - "dialog 2"
  "pc":
    texture: "actor_size"
    index: 1
    x: 48
    y: 184
    script:
    - "pc"
    - "dialog 1"
  "books":
    texture: "actor_size"
    index: 2
    x: 112
    y: 188
    script:
    - "books"
    - "dialog 1"
  "books_2":
    texture: "actor_size"
    index: 3
    x: 129
    y: 188
    script:
    - "books"
    - "dialog 1"
wildEncounters: []