ident: "overworld"
index: 0
triggers:
- type: "Collision"
  x: 352
  y: 240
  width: 128
  height: 64
  idx: -1
- type: "Collision"
  x: 318
  y: 240
  width: 18
  height: 64
  idx: -1
- type: "Collision"
  x: 336
  y: 260
  width: 16
  height: 44
  idx: -1
- type: "Teleport"
  x: 336
  y: 240
  width: 16
  height: 20
  idx: 1
- type: "Teleport"
  x: 67
  y: 606
  width: 77
  height: 32
  idx: 1
- type: "Teleport"
  x: 273
  y: 764
  width: 46
  height: 39
  idx: 2
- type: "Teleport"
  x: 528
  y: 280
  width: 88
  height: 48
  idx: 0
- type: "Collision"
  x: 191
  y: 526
  width: 66
  height: 61
  idx: -1
- type: "Actor"
  x: 453
  y: 64
  width: 31
  height: 74
  idx: 0
teleports:
  - map: 1
    target: 0
  - map: 0
    target: 2
  - map: 0
    target: 1
actors:
  "joey":
    texture: "youngster"
    index: 0
    x: 451
    y: 137
    script:
      - "joey"
      - "title joey"
      - "dialog 2"
      - "title player"
      - "dialog 1"
      - "title joey"
      - "dialog 1"
      - "battle joey"
      - "disable trigger"