ident: "route1"
index: 7
triggers:
- type: "Teleport"
  x: 620
  y: 185
  width: 20
  height: 149
  idx: 0
- type: "Collision"
  x: 531
  y: 172
  width: 109
  height: 12
  idx: -1
- type: "Collision"
  x: 531
  y: 62
  width: 6
  height: 120
  idx: -1
- type: "Collision"
  x: 91
  y: 62
  width: 443
  height: 11
  idx: -1
- type: "Collision"
  x: 91
  y: 69
  width: 7
  height: 160
  idx: -1
- type: "Collision"
  x: 36
  y: 216
  width: 57
  height: 13
  idx: -1
- type: "Collision"
  x: 91
  y: 286
  width: 5
  height: 141
  idx: -1
- type: "Collision"
  x: 94
  y: 285
  width: 3
  height: 140
  idx: -1
- type: "Collision"
  x: 36
  y: 217
  width: 4
  height: 507
  idx: -1
- type: "Collision"
  x: 36
  y: 714
  width: 193
  height: 11
  idx: -1
- type: "Collision"
  x: 228
  y: 417
  width: 18
  height: 308
  idx: -1
- type: "Collision"
  x: 226
  y: 417
  width: 15
  height: 299
  idx: -1
- type: "Collision"
  x: 91
  y: 419
  width: 59
  height: 10
  idx: -1
- type: "Collision"
  x: 145
  y: 419
  width: 4
  height: 256
  idx: -1
- type: "Collision"
  x: 148
  y: 417
  width: 2
  height: 258
  idx: -1
- type: "Collision"
  x: 91
  y: 663
  width: 55
  height: 12
  idx: -1
- type: "Collision"
  x: 91
  y: 423
  width: 4
  height: 252
  idx: -1
- type: "Collision"
  x: 226
  y: 419
  width: 154
  height: 10
  idx: -1
- type: "Collision"
  x: 376
  y: 419
  width: 4
  height: 445
  idx: -1
- type: "Collision"
  x: 186
  y: 852
  width: 194
  height: 13
  idx: -1
- type: "Collision"
  x: 186
  y: 775
  width: 3
  height: 90
  idx: -1
- type: "Collision"
  x: 186
  y: 774
  width: 4
  height: 90
  idx: -1
- type: "Collision"
  x: 0
  y: 774
  width: 189
  height: 12
  idx: -1
- type: "Collision"
  x: 0
  y: 908
  width: 458
  height: 13
  idx: -1
- type: "Collision"
  x: 454
  y: 419
  width: 5
  height: 502
  idx: -1
- type: "Collision"
  x: 454
  y: 419
  width: 81
  height: 10
  idx: -1
- type: "Collision"
  x: 531
  y: 337
  width: 4
  height: 92
  idx: -1
- type: "Collision"
  x: 531
  y: 338
  width: 109
  height: 10
  idx: -1
- type: "WildEncounter"
  x: 153
  y: 415
  width: 72
  height: 89
  idx: 0
- type: "WildEncounter"
  x: 383
  y: 418
  width: 70
  height: 126
  idx: 0
- type: "WildEncounter"
  x: 384
  y: 636
  width: 68
  height: 126
  idx: 0
- type: "WildEncounter"
  x: 152
  y: 582
  width: 73
  height: 91
  idx: 0
- type: "WildEncounter"
  x: 42
  y: 543
  width: 48
  height: 129
  idx: 0
- type: "WildEncounter"
  x: 42
  y: 230
  width: 61
  height: 56
  idx: 0
- type: "WildEncounter"
  x: 283
  y: 865
  width: 103
  height: 42
  idx: 0
- type: "WildEncounter"
  x: 115
  y: 787
  width: 70
  height: 119
  idx: 0
- type: "Water"
  x: 178
  y: 132
  width: 280
  height: 208
  idx: -1
- type: "Collision"
  x: 169
  y: 128
  width: 9
  height: 217
  idx: -1
- type: "Collision"
  x: 169
  y: 339
  width: 295
  height: 6
  idx: -1
- type: "Collision"
  x: 455
  y: 127
  width: 9
  height: 217
  idx: -1
- type: "Collision"
  x: 170
  y: 127
  width: 291
  height: 7
  idx: -1
- type: "Actor"
  x: 232
  y: 345
  width: 16
  height: 57
  idx: 0
- type: "Actor"
  x: 112
  y: 313
  width: 54
  height: 17
  idx: 1
- type: "Actor"
  x: 306
  y: 88
  width: 12
  height: 41
  idx: 2
- type: "Actor"
  x: 153
  y: 555
  width: 65
  height: 6
  idx: 3
- type: "Actor"
  x: 395
  y: 849
  width: 15
  height: 47
  idx: 4
- type: "Actor"
  x: 89
  y: 890
  width: 66
  height: 13
  idx: 5
teleports:
- map: 0
  target: 4
actors:
  "Gargamel":
    texture: "youngster_r"
    index: 5
    x: 69
    y: 885
    script: []
  "Peter":
    texture: "youngster_r"
    index: 1
    x: 94
    y: 313
    script: []
  "Gisela":
    texture: "youngster_u"
    index: 2
    x: 303
    y: 68
    script: []
  "Gertrude":
    texture: "youngster"
    index: 4
    x: 393
    y: 899
    script: []
  "Günther":
    texture: "youngster_l"
    index: 3
    x: 222
    y: 548
    script: []
  "Julian":
    texture: "youngster"
    index: 0
    x: 231
    y: 406
    script: []
wildEncounters:
- - speciesId: "machop"
    nickname: null
    level: 15
    exp: 0
    moveIds:
    - "lowsweep"
    - "vitalthrow"
    uuid: -1
    battleState: null
  - speciesId: "charizard"
    nickname: null
    level: 16
    exp: 0
    moveIds:
    - "heatwave"
    - "firefang"
    uuid: -1
    battleState: null