ident: "school"
index: 4
triggers:
- type: "Teleport"
  x: 84
  y: 0
  width: 31
  height: 13
  idx: 0
- type: "Collision"
  x: 116
  y: 2
  width: 81
  height: 4
  idx: -1
- type: "Collision"
  x: 193
  y: 3
  width: 4
  height: 171
  idx: -1
- type: "Collision"
  x: 1
  y: 2
  width: 84
  height: 4
  idx: -1
- type: "Collision"
  x: 2
  y: 3
  width: 5
  height: 173
  idx: -1
- type: "Collision"
  x: 5
  y: 170
  width: 189
  height: 4
  idx: -1
- type: "Collision"
  x: 176
  y: 138
  width: 18
  height: 7
  idx: -1
- type: "Collision"
  x: 150
  y: 143
  width: 29
  height: 7
  idx: -1
- type: "Collision"
  x: 134
  y: 137
  width: 18
  height: 8
  idx: -1
- type: "Collision"
  x: 50
  y: 139
  width: 16
  height: 10
  idx: -1
- type: "Collision"
  x: 23
  y: 145
  width: 26
  height: 8
  idx: -1
- type: "Collision"
  x: 5
  y: 138
  width: 20
  height: 8
  idx: -1
- type: "Collision"
  x: 68
  y: 20
  width: 0
  height: 0
  idx: -1
- type: "Collision"
  x: 89
  y: 104
  width: 22
  height: 15
  idx: -1
- type: "Collision"
  x: 55
  y: 89
  width: 11
  height: 8
  idx: -1
- type: "Collision"
  x: 24
  y: 89
  width: 8
  height: 7
  idx: -1
- type: "Collision"
  x: 24
  y: 55
  width: 8
  height: 9
  idx: -1
- type: "Collision"
  x: 55
  y: 55
  width: 10
  height: 9
  idx: -1
- type: "Collision"
  x: 24
  y: 23
  width: 8
  height: 10
  idx: -1
- type: "Collision"
  x: 58
  y: 25
  width: 5
  height: 7
  idx: -1
- type: "Collision"
  x: 137
  y: 25
  width: 7
  height: 6
  idx: -1
- type: "Collision"
  x: 169
  y: 24
  width: 5
  height: 8
  idx: -1
- type: "Collision"
  x: 169
  y: 55
  width: 6
  height: 7
  idx: -1
- type: "Collision"
  x: 169
  y: 89
  width: 6
  height: 8
  idx: -1
- type: "Collision"
  x: 137
  y: 89
  width: 7
  height: 8
  idx: -1
- type: "Collision"
  x: 68
  y: 146
  width: 65
  height: 16
  idx: -1
teleports:
- map: 0
  target: 2
actors:
  "teacher":
    texture: "actor_size"
    index: 0
    x: 85
    y: 121
    script:
      - "teacher"
      - "dialog 2"
  "kid_TL":
    texture: "actor_size"
    index: 1
    x: 53
    y: 68
    script:
      - "kid_TL"
      - "dialog 1"
  "kid_BL":
    texture: "actor_size"
    index: 2
    x: 53
    y: 38
    script:
      - "kid_BL"
      - "dialog 1"
  "kid_BR":
    texture: "actor_size"
    index: 3
    x: 163
    y: 37
    script:
      - "kid_BR"
      - "dialog 1"
  "twin_left":
    texture: "actor_size"
    index: 4
    x: 131
    y: 69
    script:
      - "twins"
      - "dialog 1"
  "twin_right":
    texture: "actor_size"
    index: 5
    x: 149
    y: 69
    script:
      - "twins"
      - "dialog 1"
  "board":
    texture: "actor_size"
    index: 6
    x: 111
    y: 147
    script:
      - "board"
      - "dialog 3"
wildEncounters: []